### ISSUE TITLE
"java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access" errors in dispatcher logs

### ISSUE THREAD

**Issue by maschmid** [knative-extensions/eventing-kafka-broker#2994]
**Describe the bug**
Spotted a CME exception in kafka-channel-dispatcher logs

```
{
  "@timestamp": "2023-03-01T06:16:42.515Z",
  "@version": "1",
  "message": "Consumer exception context={topics=[knative-messaging-kafka.kc-stable-delay-0.sender0], consumerGroup='kafka.kc-stable-delay-0.sender0.f61db18a-760e-4d72-825f-ed7eab799962', reference=uuid: \"f61db18a-760e-4d72-825f-ed7eab799962\"\nnamespace: \"kc-stable-delay-0\"\nname: \"connection0\"\n}",
  "logger_name": "dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.ConsumerVerticle",
  "thread_name": "vert.x-kafka-consumer-thread-2317",
  "level": "ERROR",
  "level_value": 40000,
  "stack_trace": "java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2490)\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2474)\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1496)\n\tat org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1448)\n\tat io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$commit$29(KafkaReadStreamImpl.java:610)\n\tat io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$submitTaskWhenStarted$3(KafkaReadStreamImpl.java:136)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n",
  "context": {}
}
```

the exception unrolled:
```
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2490)
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2474)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1496)
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1448)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$commit$29(KafkaReadStreamImpl.java:610)
	at io.vertx.kafka.client.consumer.impl.KafkaReadStreamImpl.lambda$submitTaskWhenStarted$3(KafkaReadStreamImpl.java:136)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Not sure if the exception affected any functionality, but there were unexpected duplicates received at around the time the CME occured in logs

 **Expected behavior**
No ConcurrentModificationException should occur

 **To Reproduce**
Unknown at this time

 **Knative release version**
1.7

 **Additional context**
Installed on OpenShift via current Serverless operator https://github.com/openshift-knative/serverless-operator `main` branch (Serverless operator 1.28)

**Comment by pierDipi** [comment]
Were you doing anything special during that time to that particular subscription?

**Comment by maschmid** [comment]
no. The only unusual thing with the kc-stable-delay scenario is the receiver having a 10s delay before returning an ACK reply

**Comment by pierDipi** [comment]
I looked at the code and I don't anything obvious since every non-thread safe operation on the consumer is scheduled on the single thread executor in vertx-kafka-client

https://github.com/vert-x3/vertx-kafka-client/blob/a8c65ddc1c231b7ecbdbf93bd66dd7685e47d6b8/src/main/java/io/vertx/kafka/client/consumer/impl/KafkaReadStreamImpl.java#L115

**Comment by pierDipi** [comment]
I believe it won't affect functionality but as you said it would produce duplicates since it won't commit the offsets.

**Comment by Jamsa** [comment]
Fixed this issue by replacing the MTChannelBased Kafka Broker with a Kafka Broker.

**Comment by maschmid** [comment]
/reopen

still reproducible with 1.11
