### ISSUE TITLE
Update Mockito/Byte Buddy

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3350]
**Problem**
When trying to install dependencies using JDK 21, the tests fail because of an old Mockito/Byte Buddy version.

See logs below:
```
If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 21
JVM vendor name    : Red Hat, Inc.
JVM vendor version : 21+35
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 21+35
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 6.4.15-200.fc38.x86_64


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.io.Closeable, interface java.lang.AutoCloseable]
        at dev.knative.eventing.kafka.broker.core.utils.ShutdownTest.run(ShutdownTest.java:34)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.io.Closeable, interface java.lang.AutoCloseable]
        at dev.knative.eventing.kafka.broker.core.utils.ShutdownTest.run(ShutdownTest.java:34)
Caused by: java.lang.IllegalStateException: 

Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
        at dev.knative.eventing.kafka.broker.core.utils.ShutdownTest.run(ShutdownTest.java:34)
Caused by: java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
        at dev.knative.eventing.kafka.broker.core.utils.ShutdownTest.run(ShutdownTest.java:34)

(END)
```
Discussion of this issue can be seen here: https://cloud-native.slack.com/archives/C04LMU33V1S/p1695143322622249

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A clean install of dependencies works when using JDK 21.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
@Cali0707 to which version should we upgrade it to get the fix?

**Comment by Cali0707** [comment]
@pierDipi I think we should upgrade Mockito to at least v5.3.1, as we need Mockito to use Byte Buddy v1.14.3 or newer

**Comment by Cali0707** [comment]
I think this was resolved in a dependably update
