### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dalcorta** [knative-extensions/eventing-kafka-broker#4059]
**Describe the bug**
I created a kafka source and associated it to a knative-broker. The consumer group stays in PropagateSubscriberURI status

 **Expected behavior**
KafkaSource set to ready

 **To Reproduce**
Created a Knative Broker, added a KafkaSource and set Knative Broker as Sink

 **Knative release version 1.15**

 **Additional context**
Log in kafka-controller with excpetion

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c6aaf5]
goroutine 534 [running]:
[knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).deleteConsumerGroupMetadata(0xc00072e1e0](http://knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).deleteConsumerGroupMetadata(0xc00072e1e0), {0x261b758, 0xc00318cf60}, 0xc00095a388)
	[knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:304](http://knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:304) +0x135
[knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).FinalizeKind(0xc00072e1e0](http://knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).FinalizeKind(0xc00072e1e0), {0x261b758, 0xc00318cf60}, 0xc00095a388)
	[knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:276](http://knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:276) +0x5e5
[knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup.(*reconcilerImpl).Reconcile(0xc0007165a0](http://knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup.(*reconcilerImpl).Reconcile(0xc0007165a0), {0x261b758, 0xc00318cf30}, {0xc0028c5700, 0x33})
	[knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup/reconciler.go:249](http://knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup/reconciler.go:249) +0x3b8
[knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc000c7cb40)](http://knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc000c7cb40))

**Comment by Cali0707** [comment]
@pierDipi @creydr I don't think I will be able to get to this issue before going back to school, can one of you take a look?

/unassign

**Comment by jeremyrajan** [comment]
Any idea when this will be fixed? Or if there is a workaround.
