### ISSUE TITLE
knative-kafka-broker-dispatcher unahndled exception when processing an invalid CE

### ISSUE THREAD

**Issue by sagigrimberg** [knative-extensions/eventing-kafka-broker#4129]
**Describe the bug**
When an external producer pushes a message that is not well-formatted as a cloud event (specifically in my case a typo in the
ce_specverion header), the dispatcher throws an unhandled exception and left blocked from processing further events.

 **Expected behavior**
The expected behavior is that the invalid CE is dropped, logged, and the dispatcher continues to process more events from the kafka topic.

The exception I encountered in the log is:
```
{
  "@timestamp": "2024-10-08T20:23:00.075Z",
  "@version": "1",
  "message": "Unhandled exception",
  "logger_name": "io.vertx.core.impl.ContextImpl",
  "thread_name": "vert.x-eventloop-thread-3",
  "level": "ERROR",
  "level_value": 40000,
  "stack_trace": "java.lang.UnsupportedOperationException: null
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.InvalidCloudEvent.getSpecVersion(InvalidCloudEvent.java:49)
	at io.cloudevents.core.builder.CloudEventBuilder.from(CloudEventBuilder.java:314)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.CloudEventOverridesMutator.apply(CloudEventOverridesMutator.java:38)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.CloudEventOverridesMutator.apply(CloudEventOverridesMutator.java:28)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherMutatorChain.dispatch(RecordDispatcherMutatorChain.java:42)
	atdev.knative.eventing.kafka.broker.dispatcher.impl.consumer.UnorderedConsumerVerticle.handleRecords(UnorderedConsumerVerticle.java:133)
	at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.UnorderedConsumerVerticle.lambda$poll$1(UnorderedConsumerVerticle.java:103)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
"
}
```

 **To Reproduce**
- setup kind with quickstart
- install kafka (I used strimzi standalone)
- install knative-kafka-broker
- setup a kafka broker
- deploy a service with an associated trigger
- produce an invalid event to the broker topic:
I reproduced with:
```
$ kubectl exec -i -t -n kafka pod/my-cluster-dual-role-0 -- bash
$ echo "ce_specversionnnn:1.0,ce_id:O234-345-890,ce_source:some.source,ce_type:some.type,ce_time:2020-11-25T09:05:00Z,content-type:application/json & {"person":{"age":18}}" > /tmp/ce.txt
$ ./bin/kafka-console-producer.sh --topic knative-broker-knative-eventing-my-kafka-broker --bootstrap-server localhost:9092 --property parse.headers=true --property headers.key.separator=: --property headers.delimiter=\& < /tmp/ce.txt
```

 **Knative release version**
```
$ kn version
Version:      
Build Date:   
Git Revision: 
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.42.1-0.20240820122005-5f5f6d820b03)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v0.42.1-0.20240828134450-34f9cd384dea)
  - eventing.knative.dev/v1 (knative-eventing v0.42.1-0.20240828134450-34f9cd384dea)
 **Additional context**
Add any other context about the problem here such as proposed priority
```
In eventing-kafka-controller.yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: knative-eventing
  labels:
    app.kubernetes.io/version: "a7715ef98d623819cbe05154ae7eaabaa0667d0b"
```

**Comment by elebiodaslingshot** [comment]
Only way around this is to restart the broker statefulset from my end.
